system_prompt: |
  Answer the following question(s) exclusively with a single answer from the answer bank.
  Nothing else should be included in your response.

  Answer Bank: yes, no

scoring_functions:
  - binary_match

tags:
  - 3d
  - rotation
  - single
  - common_sense
